### ISSUE TITLE
Issue with ACL when searching

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamServer#1223]
When I list all of my virtual machines with https://nuv.la/api/virtual-machine I get only the one on which my username is in the first ACL rule.
If I give the direct uri of a virtual-machine element on which I'm not on the first ACL rule I can see it but it doesn't appear on the search.

So ACL checking works but searching doesn't work correctly

**Comment by loomis** [comment]
How are the VirtualMachine resources inserted into the database?  Directly via the Elasticsearch Java/REST API or via the es-binding with clojure?  Some of the documents appear to have the magic `:_acl-users` and `:_acl-roles` fields while others do not.

**Comment by loomis** [comment]
From looking through the code, it appears that the virtual machine resources are inserted through the CIMI interface (via the SscljProxy on the java side).

Based on this, I've created a test in the `ssclj/jar` repository that creates n virtual machine resources with a randomized list of users (both which users and the order of the users) in the ACL. The user 'jane' is always included in the list, although not in the same position.

The test verifies that:

 * ADMIN sees all n virtual machine resources
 * jane (always included) also sees all n virtual machine resources
 * user0 sees (0, n) virtual machine resources

So, I'm unable to reproduce this behavior with the test server.

**Comment by loomis** [comment]
The problem is related to the normalization/denormalization of the ACL into the `:_acl-users` and `:acl-roles` fields that are used internally during searches.  The essence of the problem is that the denormalization is only done when a document is created, not when the document is updated.  This means that changes to the ACL are not reflected in the denormalized fields and this causes searches on the modified documents to be incorrect.

The general edit functionality must be changed to update the denormalized ACL fields.  This probably also affects the metering resources, which are copied directly from the virtual-machine fields (including the incorrect denormalized ACL fields). 

In addition, the virtual machine code is marking "internal ADMIN" as the owner of a resource.  This should just be "internal" for the user with "ADMIN" as the role.
