### ISSUE TITLE
add the organisation attribute to the quota resource

### ISSUE THREAD

**Issue by cjdcordeiro** [slipstream/SlipStreamServer#1718]

**Comment by schaubl** [comment]
Some examples of what a new `quota` document could looks like:
1) Current:
```js
{
  "description": "Limit the maximum number of NuvlaBox record a user can create/have.",
  "limit": 1,
  "name": "Max number of NuvlaBox records for toto user",
  "resource": "NuvlaboxRecord",
  "aggregation": "count:id",
  "selection": "owner/href='user/toto'",
}
```
2) Simply adding a new `organization` attribute:
```js
{
  "description": "Limit the maximum number of NuvlaBox record a user can create/have.",
  "limit": 1,
  "name": "Max number of NuvlaBox records for toto user",
  "resource": "NuvlaboxRecord",
  "aggregation": "count:id",
  "selection": "owner/href='user/toto'",
  "organization": "SixSq",
}
```
3) Separating attributes used to build the query for the collect operation and the ones used by the quota enforcement code:
```js
{
  "description": "Limit the maximum number of NuvlaBox record a user can create/have.",
  "limit": 1,
  "name": "Max number of NuvlaBox records for toto user",
  "query": {
    "resource": "NuvlaboxRecord",
    "selection": "owner/href='user/toto'",
    "aggregation": "count:id",
  },
  "properties": {
    "organization": "SixSq",
  },
}
```
4) Same as `3.` but with a type:
```js
{
  "description": "Limit the maximum number of NuvlaBox record a user can create/have.",
  "limit": 1,
  "name": "Max number of NuvlaBox records for toto user",
  "query": {
    "resource": "NuvlaboxRecord",
    "selection": "owner/href='user/toto'",
    "aggregation": "count:id",
  },
  "type": "nuvlabox-record",
  "organization": "SixSq",
}
```

I see 3 possible implementations:
a) The `properties` map can be a open map that can be used to give more informations to the quota enforcement code. 
In this implementation no validation can be done on the "properties". 
Correspond to example `3.`.

b) The `type` attribute define a sub-spec to use which can add some attribute to the main spec. 
I don't know if in the code we can access an attribute of the request before the spec is checked so that we can build the spec to apply by combining the main spec and the sub-spec. 
This solution can be seen as a lightweight alternative of templates. 
Correspond to example `4.`.

c) We use the template mechanism. 
The resulting document will also correspond to example `4.`.

Moreover I think we should add an attribute `appliesTo` which can be a list of string or a string to define to which quota enforcement code(s) this quota apply to.
Examples:
```js
{"appliesTo": "vm"}
```
```js
{"appliesTo": 
  [
    "vm",
    "nuvlabox-record",
  ]
}
```

**Comment by schaubl** [comment]
After a discussion with @loomis we decided that we should go for the solution b) and also remove the query attributes. Instead, every Quota "type" will generate it's own query and apply it when the "collect" operation is called.
To keep the current behaviour we can add a type `generic` which will provide the `resource`, `selection` and `aggregation` attributes and use them to generate the query.

<hr/>

However to be able to satisfy the nuvlabox-record use case in the immediate term we will simply add an optional `organization` attribute to the Quota spec and update the corresponding quota validation code in the nuvlabox-record resource and in the VM quota validation code.
