### ISSUE TITLE
Implement forceful termination of launched CLI after a timeout in Java ProcessUtils.

### ISSUE THREAD

**Issue by st** [slipstream/SlipStreamServer#240]
Implement forceful termination of launched CLI after a timeout in Java ProcessUtils (connector).
If CLI doesn't respect provided timeout, (and goes zombie), Java side should kill this process.

**Comment by konstan** [comment]
This is where change should happen https://github.com/slipstream/SlipStreamServer/blob/master/jar-connector/src/main/java/com/sixsq/slipstream/util/ProcessUtils.java#L72

The problem here is to obtain the timeout the CLI was started with.  Might need to update the signature of some of execGetOutput*() methods to explicitly require the timeout.  If the CLI didn't return after timeout + (say) 2 sec - kill it with a system call and report back the collected std/err outputs.
