### ISSUE TITLE
Consolidate clojure stand-alone processes

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#317]
Need to understand why the event process died and make it rock solid

**Comment by st** [comment]
The problem that occurred during CERN tests yesterday (SlipStream crashed due to too many open file descriptors) is linked to the ssclj server.
I restarted ssclj server, and some minutes later the problem re-appeared (burst of open file descriptors).
ssclj service was stopped, and slipstream restarted. 
Interruption of service for 10 mns.
I continue investigation.

**Comment by st** [comment]
- [ ] improve error message when redirection failed (ssclj not started)

**Comment by st** [comment]
The root cause was found:
* Java and Clojure server were provoking a dead lock on trying to both connect to hsqdb instance.
By using hsql://localhost:9001/ssclj instead of hsql://localhost:9001/slipstreamdb the issue was gone.
