### ISSUE TITLE
Complete json persistence/serialization

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamServer#330]
Continuation from #320

**Comment by mebster** [comment]
Added examples of json serialisation: https://gist.github.com/mebster/e9661238d16bb268c740

**Comment by mebster** [comment]
Things that have changed that break backward compatibility include: node structure in deployment, in run nodes list replacing groups string and similar for nodeInstances. Cloud services are also a list instead of a string. Targets are now including all scripts and include inheritance proposal.

**Comment by konstan** [comment]
From the fist glance, I don't see image modules on the nodes in run deployment (only references)?  Is this intentional, or I just missed them?  So, to get targets we would then need to follow the reference and do another roundtrip to SS server.  For image run I see that the targets are there with the image module.

**Comment by loomis** [comment]
The is an opportunity to converge towards the "common" attributes that are present in all CIMI resources.   The common attributes that CIMI requires are:
 - **id**: the unique resource identifier
 - **name**: human-readable name of resource
 - **description**: human-readable description of resource
 - **created**: time stamp for creation of the resource in ISO 8601 format
 - **updated**: time stamp for last update of the resource in ISO 8601 format
 - **properties**: key/value pairs associated with resource

There is also one pseudo-attribute:
 - **resourceURI**: URI defining the type of the resource

This defines the type of the given resource and shows up as an attribute in JSON but is the name of the element in XML.

In addition, the CIMI 2.0.0 spec (in preparation) also adds these:
 - **parent**: a reference to another "owning" resource
 - **vscope**: provides a map of allowed values for particular attributes (e.g. CPU architectures)

These last two are less relevant for SlipStream in the short term, although **vscope** may be interesting for passing allowed values to clients such as the UI. 

Looking at the proposed serializations, the following changes would be necessary to have a CIMI-compatible set of common attributes:
 - [ ] rename the current **resourceUri** attribute to **id**
 - [ ] rename the current **creation** attribute to **created** and change format to ISO 8601
 - [ ] rename the current **lastModified** attribute to **updated** and change format to ISO 8601
 - [ ] **name** and **description** can remain the same, although in CIMI both of these are optional
 - [ ] **tags** would need to change to **properties** and become a map rather than a structured string; both the keys and values in the map are strings
 - [ ] create a **resourceURI** attribute (for JSON) with a URI defining the type (e.g. "http://<span></span>slipstream.sixsq.com/cimi/1/Image").  This would be an &lt;Image xmlns="http://<span></span>slipstream.sixsq.com/cimi/1"&gt;&lt;/Image&gt; element in XML.

**Comment by loomis** [comment]
Another CIMI convention that I think that would be useful to implement is the CIMI **ref**.  This provides a consistent mechanism for referencing other resources.  For the JSON serialization it looks like:
```json
{
  "id": "some/resource",
  ...other resource attributes...
  "children": [
    {
      "href": "some/other/resource/id",
      ...other referenced attributes...
    }
  ] 
```
This allows simple mechanism allows:
 - To minimize the size by including only the "href" itself (requiring a client to then fetch the referenced resource separately),
 - To include the referenced resource attributes directly in the same map (increasing the size, but giving all information to the client without the need of another request), and
 - To override certain attributes in a referenced resource (e.g. changing the default RAM size) by having a client specify just those attributes directly.
 
For an XML serialization, the **href** attribute become an attribute on the enclosing element.  (Where for a list you would have, for example, &lt;child /&gt; elements.)

**Comment by loomis** [comment]
Needs to be demoed and merged.
