### ISSUE TITLE
discuss allowing runs to be deleted

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#352]
A recurring question in SlipStream tutorials is "How do I delete a run?".  This comes up primarily because people want to keep their dashboard clear of runs that they are no longer interested in.

The minimal solution would be to add a flag to the run that marks a run as deleted and would not be returned in lists of runs by default.  This would hide the run, but retain all of the information associated with it (including the log files).

A more involved solution would allow the run to actually be deleted, removing the information from the database and deleting any log files associated with it.  Such an implementation would require a check that all of the allocated resources have been freed before deleting the run.  It would also require us to distinguish the "terminate" action from the "delete" action in the API, possibly changing the current semantics of the API.

This issue should start with a discussion of the desirability of this feature and its scope.  An issue should then be created for the implementation, which possibly could be treated as part of the switch from v2 to v3 of SlipStream.

**Comment by rbf** [comment]
> The minimal solution would be to add a flag to the run that marks a run as deleted and would not be returned in lists of runs by default. This would hide the run, but retain all of the information associated with it (including the log files).

For reference, there is an open discussion about add filtering features in the dashboard tables, see slipstream/SlipStreamUI#252. One of the filters would be running/terminated runs.

**Comment by konstan** [comment]
On a heavily used SS instance the size of the SS DB eventually grows and this creates different issues (https://github.com/slipstream/SlipStreamServer/issues/725, https://github.com/SixSq/tasklist/issues/777) on running the DBMS (hsqldb in our case). 

We need to introduce retirement (cleanup/deletion) of the old runs.  Maybe a simple cleanup of the values of the RTPs on the “old” runs can already reduce the size of the db.

Here is the case of the DB on https://bb1.hnx.helix-nebula.eu where the size of DB is almost 1GB now

```[root@bluebox SlipStreamDB]# ll -h slipstreamdb.script slipstreamdb.log
-rw-r--r-- 1 slipstream slipstream 301K May 24 16:01 slipstreamdb.log
-rw-r--r-- 1 slipstream slipstream 953M May 24 11:10 slipstreamdb.script
[root@bluebox SlipStreamDB]#
```
NB! I had to set Xmx to 5GB on BB, otherwise slipstream DB wouldn’t start with OOM.
