### ISSUE TITLE
test server using postgresql

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#385]
Test that the SlipStream server behaves correctly when pointed to a postgresql database.  Ensure that the correct database configuration is available for both the java and clojure sides.

**Comment by konstan** [comment]
During the server startup, test for the existence of the user `super` fails in the `User.load()` with
```org.postgresql.util.PSQLException: ERROR: column user0_.resourceuri does not exist```

Checking in the DB, the `User` table is not there, while in the debugging mode it's possible to see that hibernate executes the corresponding `CREATE` statement:
```
Hibernate: 
    create table User (
        resourceuri varchar(255) not null,
        category int4,
        creation timestamp,
        deleted boolean not null,
        description varchar(1024),
        jpaVersion int4 not null,
        lastModified timestamp,
        activeSince timestamp,
        email varchar(255),
        firstName varchar(255),
        isSuperUser boolean not null,
        lastExecute timestamp,
        lastName varchar(255),
        lastOnline timestamp,
        name varchar(255),
        organization varchar(255),
        password varchar(255),
        state varchar(255),
        primary key (resourceuri)
    )
```
It turns out that in the PostgreSQL `USER` is a reserved key word http://www.postgresql.org/docs/9.4/static/sql-keywords-appendix.html.  However, hibernate doesn't detect the table creation failure, which can be clearly seen when creating manually:

```
postgres=# CREATE DATABASE slipstream;
CREATE DATABASE
postgres=# \c slipstream 
You are now connected to database "slipstream" as user "postgres".
slipstream=# CREATE TABLE User (resourceuri varchar(255) not null);
ERROR:  syntax error at or near "User"
LINE 1: CREATE TABLE User (resourceuri varchar(255) not null);
                     ^
slipstream=#
```

The failure to detect the failure during the table creation looks to be a bug in Hibernate.

http://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql

Setting the name to the `User` entity as 'User_' and updating the named queries resolves the issue.

**Comment by konstan** [comment]
Closing.  Continues in https://github.com/SixSq/tasklist/issues/367
