### ISSUE TITLE
create input/output parameter category

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#446]
There is a need for some parameters for a node to be both input and output parameters.  A web server, for example, may want to allow the port to be specified by the person deploying the web server, but clients of the web server will also need to know this port.  It would be possible to create two parameters: an input parameter (port-in) and an output parameter (port-out), but this is awkward.  Having a parameter that serves as both an input and output parameter makes clear how the parameter will be used without introducing unnecessary duplication.

As these parameters can also function as input parameters, they must be able to be modified when starting an application from the run dialog. (See slipstream/SlipStreamUI#402.)

**Comment by rbf** [comment]
I was thinking if it wouldn't make sense that all input parameters are directly also usable as output parameters, but this pointed me a simpler scenario where there are no `input`, `output` and `input/output` parameters, but only `parameters`, which might be `editable on deployment`. All parameters would then always be accessible as `nodename.parametername`.

**Comment by schaubl** [comment]
What I do in that case is the following: 
I create the parameter as an `Input` one and then I use `ss-get --noblock input-param-name` to retreive the value. If this is a password I generate a password and then I use `ss-set -input-param-name password` to update the parameter.

Since if a parameter is of type `input` or `output` change only it's visibility in the "_Deploy ..._" dialog (and in the _Node_ of an _Application_) I would suggest to transform the dropdown menu `Input/Output` to a checkbox called for example **`editable`** to tell if the user can change it's value from the UI or not.
