### ISSUE TITLE
evaluate yada

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamServer#630]
Evaluate the use of [yada](https://github.com/juxt/yada) for serving the CIMI resources in the SlipStream server. Specifically determine:

 - [ ] Can yada easily provide the standard SCRUD actions for the standard CIMI resources we have in SlipStream?
 - [ ] Can the routing/actions easily be created dynamically, as is currently done in the server? 
 - [ ] How much modification is required in our current code base to switch to using yada?
 - [ ] Is it possible to take advantage of the yada's [swagger](http://swagger.io) support?  If so, what needs to change to take advantage of this?

This task should produce an estimate of the effort required to adopt yada as well as a list of actions to do so.

**Comment by st** [comment]
1) Can yada easily provide the standard SCRUD actions for the standard CIMI resources we have in SlipStream?

We will need to adapt a lot of code (using resource model in yada) and plug our current standard implementations for
:get, :put, ....

{:properties {…}
 :methods {:get {:response (fn [ctx] "Hello World!")}
           :put {…}
           :brew {…}}
 …
})

2) Can the routing/actions easily be created dynamically, as is currently done in the server?
Using bidi is the recommended way:
"However, yada is designed to work especially well with its sister library bidi, and unless you have a strong reason to use an alternative routing library, you should stay with the default."

bidi handlers compatible with ring handlers
;; (wrap-dummy-logger (bidi/make-handler api))


3) How much modification is required in our current code base to switch to using yada?

It looks a very specific way of exposing REST resources ("resources as data").
So, the effort is probably big.

4) Is it possible to take advantage of the yada's swagger support? If so, what needs to change to take advantage of this?
yada uses Ring-Swagger.
See also ring-swagger-ui.

Actions:
* prototype ring-swagger/ring-swagger-ui    : 5
No need for yada for this

* try adding a "yada" resource co-existing with current ones ? : 5
* try migrating current resources to yada ?     : 8

General remarks :
"The reason it does so is that the swagger support in
yada only works when you use bidi, because yada and bidi provide the yin
and yang of data (routes and resources) that a Swagger spec. exposes.""
